server:
  port: 80
  contextPath: /api

services:
  auth:
    baseUrl: http://localhost:9998

security:
  oauth2:
    client:
      client-id: expenses-tracker-service
      client-secret: j982hsf#sjfjvoln3r3ofhslfnsofhbbOO
      access-token-uri: ${services.auth.baseUrl}/oauth/token
      user-authorization-uri: ${services.auth.baseUrl}/oauth/authorize
    resource:
      user-info-uri: ${services.auth.baseUrl}/me

logging:
  level:
    org.springframework.security: ERROR

---
spring:
  profiles: dev
server:
  port: 9999
logging:
  level:
    org.springframework.security: DEBUG