server:
  port: 80
  contextPath: /api

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate

  datasource:
      url: jdbc:postgresql://0.0.0.0:5432/test
      username: test
      password: test
      driver-class-name: org.postgresql.Driver

services:
  auth:
    baseUrl: http://localhost:9998

security:
  oauth2:
    client:
      client-id: expenses-tracker-service
      client-secret: expenses-tracker-service-secret
      access-token-uri: ${services.auth.baseUrl}/oauth/token
      user-authorization-uri: ${services.auth.baseUrl}/oauth/authorize
    resource:
      jwt:
        keyUri: ${services.auth.baseUrl}/oauth/token_key

logging:
  level:
    org.springframework.security: ERROR

---
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 9999
logging:
  level:
    org.springframework.security: DEBUG