server:
  contextPath: /api
  port: 9999

services:
  auth:
    baseUrl: http://localhost:9998

security:
  oauth2:
    client:
      client-id: expenses-tracker-service
      client-secret: j982hsf#sjfjvoln3r3ofhslfnsofhbbOO
      access-token-uri: ${services.auth.baseUrl}/oauth/token
      user-authorization-uri: ${services.auth.baseUrl}/oauth/authorize
    resource:
      user-info-uri: ${services.auth.baseUrl}/me